title: 6.110 Spring 2024
description: Course website for 6.110 Spring 2024
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: https://6110-sp24.github.io

aux_links:
  GitHub: https://github.com/6110-sp24/
  Piazza: https://piazza.com/class/ls0no6nhtr817n
  Gradescope: https://www.gradescope.com/courses/727449

nav_external_links:
  - title: GitHub
    url: https://github.com/6110-sp24/
  - title: Piazza
    url: https://piazza.com/class/ls0no6nhtr817n
  - title: Gradescope
    url: https://www.gradescope.com/courses/727449

collections:
  pages:
    output: true
    permalink: /:name
  notes:
    output: true
    permalink: /:collection/:name

# Set up the _pages collection to host most course-related pages
# Home is in index.md
defaults:
  # Default values to apply to all _pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
  - scope:
      path: ""
      type: "notes"
    values:
      layout: note

# Make just_the_docs aware of the _pages collection
just_the_docs:
  collections:
    pages:
      name: Pages
    notes:
      name: Notes